name: Get latest release version

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 10 * * *'

jobs:

  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Fetch release version
        run: |
          echo VERSION=$(curl -sL https://api.github.com/repos/pi-hole/docker-pi-hole/releases/latest | \
            jq -r ".tag_name") > $GITHUB_ENV

      - name: Update README.md
        run: |
          sed -i -E "s|(pombeirp/pihole-dote):.*$|\1:${{ env.VERSION }}|g" README.md

      - name: Check for modified files
        id: git-check
        run: echo "modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")" > ${GITHUB_OUTPUT}

      - name: Commit and tag latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Pedro Pombeiro'
          git config --global user.email 'pedropombeiro@users.noreply.github.com'
          git add README.md
          git commit -m 'New release version'
          git tag "v${{ env.VERSION }}"
          git push
          git push --tags
